# This docker compose file is intended to be run onboard the ROV's Raspberry Pi.
services:
  eer_ros_packages:
    build:
      context: ./ros_workspace
      dockerfile: Dockerfile
    tty: true
    container_name: eer_ros_packages
    restart: always
    ipc: host # Required for ros2 communication with host network
    privileged: true # Required for access to the USB-to-Serial adapter for UART
    volumes:
      - /dev:/dev # Required for access to the USB-to-Serial adapter for UART (ttyUSB0)
      - ./ros_workspace/src/common_backend/common_backend/config:/app/src/common_backend/common_backend/config # Mount the config directory so that it persists between container restarts
      - ./configs:/app/configs 
      - ~/.ssh/:/root/.ssh
    networks:
      macvlan_net:
        ipv4_address: 192.168.137.250

networks:
  macvlan_net:
    external: true