services:
  bluestar_backend:
    build:
      context: ./ros_workspace
      dockerfile: Dockerfile
    tty: true
    container_name: bluestar_backend
    restart: always
    ipc: host # Required for ros2 communication with host network
    privileged: true # Required for access to the i2c bus
    volumes:
      - /dev:/dev # Allow access to the i2c bus
      - ./configs:/app/configs 
      - ~/.ssh/:/root/.ssh
    entrypoint: ["/bin/bash", "/app/docker_backend_entry_script.sh"]
  bluestar_frontend:
    build:
      context: ./ros_workspace
      dockerfile: Dockerfile
    tty: true
    container_name: bluestar_frontend
    ipc: host
    environment:
      - DISPLAY=:99
      - VNC_PORT=5900
      - VNC_RESOLUTION=1280x720x24
      - XDG_RUNTIME_DIR=/tmp/xdg
    ports:
      - "5900:5900"
    volumes:
      - ./configs:/app/configs
    entrypoint: ["/bin/bash", "/app/docker_frontend_entry_script.sh"]

    